#!/bin/bash
# Rspamd
# ------
#
# Rspamd is a fast, modern spam-filtering system. It replaces SpamAssassin,
# OpenDKIM, OpenDMARC and postgrey in a single daemon:
#
#  * Content scanning (Bayes, regex, fuzzy, RBLs, ...) like SpamAssassin
#  * DKIM signing on outbound mail like OpenDKIM
#  * DKIM, SPF and DMARC verification like OpenDKIM/OpenDMARC
#  * Greylisting like postgrey
#
# Rspamd talks to Postfix as a milter. Mail accepted by Postfix is delivered
# straight to Dovecot via LMTP; there is no spampd hop any more.
#
# Bayes data and statistics are stored in Redis.

source setup/functions.sh # load our functions
source /etc/mailinabox.conf # load global vars

# ### Migration: deactivate the old anti-spam stack
#
# Mail-in-a-Box used to ship spampd + SpamAssassin, OpenDKIM, OpenDMARC
# and postgrey. On a re-run / upgrade we stop & disable those services
# so they don't fight rspamd over milter ports, but we deliberately
# DO NOT purge the packages and DO NOT delete their data under
# $STORAGE_ROOT (SpamAssassin Bayes files, postgrey DB), nor their
# /etc configs. That keeps an in-place rollback possible: re-running
# the previous setup will re-enable everything from where it left off.
#
# If you want to reclaim that disk/packages later, do it manually:
#   apt purge spampd opendkim opendmarc postgrey razor pyzor \
#             dovecot-antispam libmail-dkim-perl
#   rm -rf "$STORAGE_ROOT/mail/spamassassin" "$STORAGE_ROOT/mail/postgrey"

for svc in spampd opendkim opendmarc postgrey; do
	if systemctl list-unit-files "$svc.service" >/dev/null 2>&1; then
		systemctl stop "$svc" 2>/dev/null || true
		systemctl disable "$svc" 2>/dev/null || true
	fi
done

# Remove only the dovecot drop-in that wired SpamAssassin learning via
# the antispam plugin -- it's recreated by the legacy setup script on
# rollback, so deleting it here is safe.
rm -f /etc/dovecot/conf.d/99-local-spampd.conf

# Drop the legacy dovecot antispam plugin reference from 20-imap.conf /
# 20-pop3.conf. The legacy setup script re-injects it on rollback.
for f in /etc/dovecot/conf.d/20-imap.conf /etc/dovecot/conf.d/20-pop3.conf; do
	if [ -f "$f" ]; then
		sed -i 's/ antispam//g' "$f"
	fi
done

# ### Install packages.

echo "Installing Rspamd..."
apt_install rspamd redis-server opendkim-tools

# Use the official Rspamd repository on supported Ubuntu releases if available;
# fall back to the distro package otherwise. We rely on the distro for simplicity.

# ### Redis (Bayes + greylisting + ratelimit + neural backend)
#
# Bind Redis to localhost only, persist its data under STORAGE_ROOT so it
# survives reinstalls and is included in backups.

mkdir -p "$STORAGE_ROOT/mail/rspamd/redis"
chown -R redis:redis "$STORAGE_ROOT/mail/rspamd/redis"

tools/editconf.py /etc/redis/redis.conf -s \
	bind="127.0.0.1 ::1" \
	dir="$STORAGE_ROOT/mail/rspamd/redis" \
	maxmemory-policy=noeviction

restart_service redis-server

# ### DKIM key
#
# Re-use the existing DKIM key generated by previous installs (kept under
# $STORAGE_ROOT/mail/dkim/mail.private) so DNS records remain valid. Create
# a new 2048-bit RSA key if none exists. opendkim-tools provides the keygen
# utility (rspamadm also has dkim_keygen but the file layout matches what
# previous installs already shipped).

mkdir -p "$STORAGE_ROOT/mail/dkim"
if [ ! -f "$STORAGE_ROOT/mail/dkim/mail.private" ]; then
	opendkim-genkey -b 2048 -r -s mail -D "$STORAGE_ROOT/mail/dkim"
fi
chown -R _rspamd:_rspamd "$STORAGE_ROOT/mail/dkim"
chmod 700 "$STORAGE_ROOT/mail/dkim"
chmod 600 "$STORAGE_ROOT/mail/dkim/mail.private"

# ### Bayes storage path
#
# Bayes data lives in Redis (under $STORAGE_ROOT/mail/rspamd/redis), so it is
# automatically included in backups.

mkdir -p "$STORAGE_ROOT/mail/rspamd"
chown -R _rspamd:_rspamd "$STORAGE_ROOT/mail/rspamd"

# ### Rspamd configuration
#
# All overrides live in /etc/rspamd/local.d (merged with the shipped defaults
# in /etc/rspamd/) and /etc/rspamd/override.d (replaces the shipped defaults).

mkdir -p /etc/rspamd/local.d /etc/rspamd/override.d

# Worker that exposes the milter protocol to Postfix on TCP 11332.
cat > /etc/rspamd/local.d/worker-proxy.inc << EOF
bind_socket = "127.0.0.1:11332";
milter = yes;
timeout = 120s;
upstream "local" {
  default = yes;
  self_scan = yes;
}
EOF

# Controller worker (for rspamc, training and the web UI). Bound to localhost
# only; no password set since access is restricted to local clients.
cat > /etc/rspamd/local.d/worker-controller.inc << EOF
bind_socket = "127.0.0.1:11334";
secure_ip = "127.0.0.1";
secure_ip = "::1";
EOF

# Normal worker (used by the proxy in self_scan mode).
cat > /etc/rspamd/local.d/worker-normal.inc << EOF
bind_socket = "127.0.0.1:11333";
EOF

# Redis storage for stats / fuzzy / greylist / neural / ratelimit.
cat > /etc/rspamd/local.d/redis.conf << EOF
servers = "127.0.0.1";
EOF

# Bayes classifier, backed by Redis. Train per-user is disabled so all users
# share one set of training data (matches the previous SpamAssassin behaviour).
cat > /etc/rspamd/local.d/classifier-bayes.conf << EOF
backend = "redis";
servers = "127.0.0.1";
new_schema = true;
autolearn = true;
EOF

# Action thresholds. greylist replaces postgrey; add_header marks the message
# as spam (X-Spam: Yes) so the sieve script files it into the Spam folder;
# reject drops obvious spam at SMTP time.
cat > /etc/rspamd/local.d/actions.conf << EOF
greylist = 4;
add_header = 6;
reject = 15;
EOF

# Make sure milter_headers adds an X-Spam header on messages whose action is
# >= add_header, so the dovecot sieve script can file them into Spam.
cat > /etc/rspamd/local.d/milter_headers.conf << EOF
use = ["x-spamd-bar", "x-spam-level", "authentication-results", "x-spam-status"];
authenticated_headers = ["authentication-results"];
extended_spam_headers = true;
skip_local = false;
skip_authenticated = false;
EOF

# DKIM signing for outbound mail. One key signs all domains (the same private
# key the previous OpenDKIM setup used); the DKIM DNS record is published
# per-domain by the management daemon.
cat > /etc/rspamd/local.d/dkim_signing.conf << EOF
enabled = true;
selector = "mail";
path = "$STORAGE_ROOT/mail/dkim/mail.private";
allow_username_mismatch = true;
use_domain = "header";
sign_networks = ["127.0.0.0/8", "::1"];
sign_authenticated = true;
EOF

# Disable ARC signing for simplicity (we are not a forwarder).
cat > /etc/rspamd/local.d/arc.conf << EOF
enabled = false;
EOF

# DMARC reporting off by default (the previous install also didn't send DMARC
# reports). DMARC verification is still applied to inbound mail.
cat > /etc/rspamd/local.d/dmarc.conf << EOF
reporting {
  enabled = false;
}
EOF

# Greylisting: 3 minutes, like the postgrey replacement (legit MTAs retry).
cat > /etc/rspamd/local.d/greylist.conf << EOF
expire = 1d;
timeout = 3min;
EOF

# Tell rspamd to use the storage directory for its own variable data
# (statefiles for fuzzy storage etc.).
tools/editconf.py /etc/default/rspamd \
	CONFDIR=/etc/rspamd \
	RUNDIR=/run/rspamd \
	DBDIR="$STORAGE_ROOT/mail/rspamd" \
	LOGDIR=/var/log/rspamd \
	2>/dev/null || true

# ### Dovecot integration: spam/ham learning via IMAPSieve
#
# When a user moves a message into the Spam folder, dovecot triggers a sieve
# script that pipes the message to `rspamc learn_spam`. Moving it out of the
# Spam folder triggers `rspamc learn_ham`.

# Enable imap_sieve and sieve_extprograms in Dovecot.
sed -i "s/#mail_plugins = .*/mail_plugins = \$mail_plugins imap_sieve/" /etc/dovecot/conf.d/20-imap.conf

cat > /etc/dovecot/conf.d/90-sieve-rspamd.conf << EOF
plugin {
  sieve_plugins = sieve_imapsieve sieve_extprograms
  sieve_extensions = +vnd.dovecot.pipe +vnd.dovecot.environment

  imapsieve_mailbox1_name = Spam
  imapsieve_mailbox1_causes = COPY APPEND
  imapsieve_mailbox1_before = file:/etc/dovecot/sieve/learn-spam.sieve

  imapsieve_mailbox2_name = *
  imapsieve_mailbox2_from = Spam
  imapsieve_mailbox2_causes = COPY
  imapsieve_mailbox2_before = file:/etc/dovecot/sieve/learn-ham.sieve

  sieve_pipe_bin_dir = /etc/dovecot/sieve/bin
  sieve_global_extensions = +vnd.dovecot.pipe +vnd.dovecot.environment
}
EOF

mkdir -p /etc/dovecot/sieve /etc/dovecot/sieve/bin

cat > /etc/dovecot/sieve/learn-spam.sieve << 'EOF'
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment", "variables"];
if environment :matches "imap.user" "*" { set "username" "${1}"; }
pipe :copy "rspamc-learn-spam.sh" [ "${username}" ];
EOF

cat > /etc/dovecot/sieve/learn-ham.sieve << 'EOF'
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment", "variables"];
if environment :matches "imap.mailbox" "*" { set "mailbox" "${1}"; }
if string "${mailbox}" "Trash" { stop; }
if environment :matches "imap.user" "*" { set "username" "${1}"; }
pipe :copy "rspamc-learn-ham.sh" [ "${username}" ];
EOF

cat > /etc/dovecot/sieve/bin/rspamc-learn-spam.sh << 'EOF'
#!/bin/sh
exec /usr/bin/rspamc learn_spam
EOF

cat > /etc/dovecot/sieve/bin/rspamc-learn-ham.sh << 'EOF'
#!/bin/sh
exec /usr/bin/rspamc learn_ham
EOF

chmod +x /etc/dovecot/sieve/bin/rspamc-learn-spam.sh /etc/dovecot/sieve/bin/rspamc-learn-ham.sh

# Pre-compile the learning sieve scripts so dovecot does not need to do it
# at first use (when it may not have permission anyway).
sievec /etc/dovecot/sieve/learn-spam.sieve
sievec /etc/dovecot/sieve/learn-ham.sieve

chown -R mail:dovecot /etc/dovecot/sieve

# ### Postfix milter wiring
#
# Connect Postfix to the rspamd proxy worker (TCP 11332) as a milter.
# Both incoming (smtpd_milters) and outgoing (non_smtpd_milters) mail is
# scanned so outbound DKIM signatures are added by rspamd's dkim_signing
# module.
tools/editconf.py /etc/postfix/main.cf \
	"smtpd_milters=inet:127.0.0.1:11332" \
	non_smtpd_milters=\$smtpd_milters \
	milter_default_action=accept \
	milter_protocol=6 \
	milter_mail_macros="i {mail_addr} {client_addr} {client_name} {auth_authen}" \
	milter_rcpt_macros="i {rcpt_addr}"

# Make sure rspamd autostarts and is running.
hide_output systemctl enable rspamd
restart_service rspamd
restart_service postfix
restart_service dovecot
